namespace Hypercooled.Shared.Textures
{
	public enum TextureAlphaBlendType : sbyte
	{
		TEXBLEND_DEFAULT = -1,
		TEXBLEND_SRCCOPY = 0,
		TEXBLEND_BLEND = 1,
		TEXBLEND_ADDATIVE = 2,
		TEXBLEND_SUBTRACTIVE = 3,
		TEXBLEND_OVERBRIGHT = 4,
		TEXBLEND_DEST_BLEND = 5,
		TEXBLEND_DEST_ADDATIVE = 6,
		TEXBLEND_DEST_SUBTRACTIVE = 7,
		TEXBLEND_DEST_OVERBRIGHT = 8,
	}
}
